services:
  server:
    build: .
    network_mode: host

    ports:
      - "8083:8083"
    depends_on:
      - db
  
  db:
    image: postgres:latest
    network_mode: host
    # tty: true
    # stdin_open: true
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5332:5332"
      - "5432:5432"
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: