definitions:
  ByteStringFromHex:
    description: Bytes encoded in hex.
    format: hex
    type: string
  ExpModProofInput:
    properties:
      piPubE:
        exclusiveMinimum: false
        minimum: 0
        type: integer
      piPubN:
        exclusiveMinimum: false
        minimum: 0
        type: integer
      piSignature:
        exclusiveMinimum: false
        minimum: 0
        type: integer
      piTokenName:
        exclusiveMinimum: false
        minimum: 0
        type: integer
    required:
    - piPubE
    - piPubN
    - piSignature
    - piTokenName
    type: object
  KeyID:
    description: Encrypting key ID
    example: 00000000-0000-0000-0000-000000000000
    format: uuid
    type: string
  ProofStatusSchema:
    description: Status of a submitted proof
    properties:
      contents:
        $ref: '#/definitions/ZKProveResult'
      tag:
        $ref: '#/definitions/Status'
    required:
    - contents
    - tag
    type: object
  ProverStats:
    description: Prover statistics for the last 24 hours
    properties:
      average_proof_time_seconds:
        format: double
        type: number
      longest_queue_size:
        maximum: 9223372036854775807
        minimum: -9223372036854775808
        type: integer
      total_valid_proofs:
        maximum: 9223372036854775807
        minimum: -9223372036854775808
        type: integer
    required:
    - total_valid_proofs
    - longest_queue_size
    - average_proof_time_seconds
    type: object
  PublicKey:
    description: RSA public key for encrypting ZK proof
    properties:
      public_e:
        description: Public exponent used in the RSA algorithm, as a decimal integer.
        exclusiveMinimum: false
        minimum: 0
        type: integer
      public_n:
        description: Public modulus used in the RSA algorithm, as a decimal integer.
        exclusiveMinimum: false
        minimum: 0
        type: integer
      public_size:
        description: Size of the RSA public key, in bits.
        exclusiveMinimum: false
        minimum: 0
        type: integer
    required:
    - public_size
    - public_n
    - public_e
    type: object
  PublicKeyBundle:
    description: RSA public key with its ID
    properties:
      id:
        $ref: '#/definitions/KeyID'
      public:
        $ref: '#/definitions/PublicKey'
    required:
    - id
    - public
    type: object
  Status:
    description: Status of a submitted proof
    enum:
    - Completed
    - Pending
    - Queued
    - Failed
    - NotFound
    type: string
  UTCTime:
    example: 2016-07-22T00:00:00Z
    format: yyyy-mm-ddThh:MM:ssZ
    type: string
  UUID:
    description: ID of a submitted prove request
    example: '"00000000-0000-0000-0000-000000000000"'
    format: string
    type: string
  ZKF:
    description: Field element.
    type: integer
  ZKProofBytes:
    description: Proof bytes where bytes are represented in hexadecimal encoding.
    properties:
      a_xi_int:
        type: integer
      b_xi_int:
        type: integer
      c_xi_int:
        type: integer
      cmA_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmB_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmC_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmF_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmH1_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmH2_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmQhigh_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmQlow_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmQmid_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmZ1_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      cmZ2_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      f_xi_int:
        type: integer
      h1_xi'_int:
        type: integer
      h2_xi_int:
        type: integer
      l1_xi:
        $ref: '#/definitions/ZKF'
      l_xi:
        items:
          $ref: '#/definitions/ZKF'
        type: array
      proof1_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      proof2_bytes:
        $ref: '#/definitions/ByteStringFromHex'
      s1_xi_int:
        type: integer
      s2_xi_int:
        type: integer
      t_xi'_int:
        type: integer
      t_xi_int:
        type: integer
      z1_xi'_int:
        type: integer
      z2_xi'_int:
        type: integer
    required:
    - cmA_bytes
    - cmB_bytes
    - cmC_bytes
    - cmF_bytes
    - cmH1_bytes
    - cmH2_bytes
    - cmZ1_bytes
    - cmZ2_bytes
    - cmQlow_bytes
    - cmQmid_bytes
    - cmQhigh_bytes
    - proof1_bytes
    - proof2_bytes
    - a_xi_int
    - b_xi_int
    - c_xi_int
    - s1_xi_int
    - s2_xi_int
    - f_xi_int
    - t_xi_int
    - t_xi'_int
    - z1_xi'_int
    - z2_xi'_int
    - h1_xi'_int
    - h2_xi_int
    - l_xi
    - l1_xi
    type: object
  ZKProveRequest:
    description: "Data required for ZK proof\nThe unencrypted payload must be a JSON
      of the following format:\n\t\n\t{                        \n\t\tpiPubE: integer,
      \      \n\t\tpiPubN: integer,       \n\t\tpiSignature: integer,  \n\t\tpiTokenName:
      integer   \n\t}                        \n\t\npiPubE is the public exponent used
      in the RSA key used to sign the JSON Web Token, as a decimal integer.\npiPubN
      is the public modulus used in the RSA key used to sign the JSON Web Token, as
      a decimal integer.\npiSignature is the signature attached to the JSON Web Token,
      as a decimal integer.\npiTokenName is the hash of the public key corresponding
      to the Wallet's root key, as a decimal integer.\n⋅\nThe Prover server uses combined
      encryption to secure sensitive information.\nPayload is encrypted with a symmetric
      cipher, while its encryption key is itself encrypted with the Server's 2048-bit
      RSA key.\n⋅\nThe JSON from above must be encrypted with AES-256-CBC and Optimal
      Asymmetric Encryption Padding(OAEP), making the \"encrypted_payload\" field.\nAES-256
      encryption key must itself be encrypted with one of the Prover server's public
      keys, making the \"aes_encryption_key\" field.\nThe key ID of the Server's RSA
      key used to encrypt the AES key makes the \"server_key_id\" field.\n⋅\n"
    properties:
      aes_encryption_key:
        description: Hex-encoded AES-256 key for decyphering the payload. The key
          should be encrypted with one of the server's RSA keys.
        format: hex
        type: string
      encrypted_payload:
        description: Hex-encoded ZK Prover input encrypted with AES-256-CBC and PKCS#7
          padding.
        format: hex
        type: string
      server_key_id:
        description: ZK Prover server public key ID used to encrypt the AES key.
        example: 00000000-0000-0000-0000-000000000000
        format: uuid
        type: string
    required:
    - server_key_id
    - aes_encryption_key
    - encrypted_payload
    type: object
  ZKProveResult:
    description: ZK proof bytes with a timestamp
    properties:
      bytes:
        $ref: '#/definitions/ZKProofBytes'
      timestamp:
        $ref: '#/definitions/UTCTime'
    required:
    - bytes
    - timestamp
    type: object
info:
  contact:
    email: info@zkfold.io
    name: zkFold Technical Support
    url: https://zkfold.io/
  description: API to interact with zkFold Prover Server
  license:
    name: Apache-2.0
    url: https://opensource.org/licenses/apache-2-0
  title: zkFold Prover Server API
  version: 0.0.1
paths:
  /v0/keys:
    get:
      produces:
      - application/json;charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            items:
              $ref: '#/definitions/PublicKeyBundle'
            type: array
      summary: Get server public keys.
      tags:
      - ZK prover endpoints
  /v0/proof-status:
    post:
      consumes:
      - application/json;charset=utf-8
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UUID'
      produces:
      - application/json;charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ProofStatusSchema'
        '400':
          description: Invalid `body`
      summary: Check the status of a proof.
      tags:
      - ZK prover endpoints
  /v0/prove:
    post:
      consumes:
      - application/json;charset=utf-8
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/ExpModProofInput'
      produces:
      - application/json;charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/UUID'
        '400':
          description: Invalid `body`
      summary: Submit unencrypted data for proving.
      tags:
      - ZK prover endpoints
  /v0/prove-encrypted:
    post:
      consumes:
      - application/json;charset=utf-8
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/ZKProveRequest'
      produces:
      - application/json;charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/UUID'
        '400':
          description: Invalid `body`
      summary: Submit encrypted data for proving.
      tags:
      - ZK prover endpoints
  /v0/stats:
    get:
      produces:
      - application/json;charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ProverStats'
      summary: Get prover statistics.
      tags:
      - ZK prover endpoints
swagger: '2.0'
tags:
- description: Retrieve server keys, submit encrypted or unencrypted proofs, and check
    proof status.
  name: ZK prover endpoints
